main:
  - name: Учиться
    URL: ru/learn
    weight: 1
    identifier: learn
  - name: Книги
    parent: learn
    URL: ru/learn/books
    weight: 2
  - name: Путь обучения
    parent: learn
    URL: ru/learn/learning-path
    weight: 3
  - name: Шаблоны
    parent: learn
    URL: ru/learn/patterns
    weight: 4
  - name: Исследования
    parent: learn
    URL: ru/learn/research
    weight: 5
  - name: События
    URL: ru/events
    weight: 2
  - name: Сообщество
    identifier: community
    URL: ru/community
    weight: 3
  - name: Истории
    URL: ru/stories
    weight: 4
  - name: Справочник услуг
    URL: ru/community/services
    parent: community
    weight: 2
  - name: О нас
    identifier: about
    URL: ru/about
    weight: 5
  - name: Объявления
    URL: ru/about/announcements
    parent: about
    weight: 1
  - name: Совет и управление
    URL: ru/about/board
    parent: about
    weight: 2
  - name: Члены
    URL: ru/about/members
    parent: about
    weight: 3
  - name: Спонсоры
    URL: ru/about/sponsors
    parent: about
    weight: 4
  - name: Кодекс поведения
    URL: ru/about/codeofconduct
    parent: about
    weight: 5
  - name: Свяжитесь с нами
    URL: ru/about/contact
    parent: about
    weight: 6
footer_left:
  - name: Учиться
    URL: ru/learn
    weight: 1
    post: bold
  - name: Книги
    URL: ru/learn/books
    weight: 2
footer_middle:
  - name: События
    URL: ru/events
    weight: 1
    post: bold
  - name: Сообщество
    URL: ru/community
    weight: 2
    post: bold
    pre: _blank
  - name: Истории
    URL: ru/stories
    weight: 3
    post: bold
  - name: Справочник услуг
    URL: ru/community/services
    weight: 4
  - name: Объявления
    URL: ru/about/announcements
    weight: 5
footer_right:
  - name: О нас
    URL: ru/about
    weight: 1
    post: bold
  - name: Совет и управление
    URL: ru/about/board
    weight: 2
  - name: Члены
    URL: ru/about/members
    weight: 3
  - name: Спонсоры
    URL: ru/about/sponsors
    weight: 4
  - name: Кодекс поведения
    URL: ru/about/codeofconduct
    weight: 5
  - name: Свяжитесь с нами
    URL: ru/about/contact
    weight: 6
  - name: Политика конфиденциальности
    URL: ru/about/privacy
    weight: 7


