baseURL: 'https://innersourcecommons.org/'
title: InnerSource Commons

pluralizeListTitles: false
menu:
  main:
    - name: Learn
      URL: learn
      weight: 1
      identifier: learn
    - name: Books
      parent: learn
      URL: learn/books
      weight: 2
    - name: Learning Path
      parent: learn
      URL: learn/learning-path
      weight: 3
    - name: Patterns
      parent: learn
      URL: learn/books/innersource-patterns
      weight: 4
    - name: Research
      parent: learn
      URL: learn/research
      weight: 5
    - name: Events
      URL: events
      weight: 2
    - name: Community
      identifier: community
      URL: community
      weight: 3
    - name: InnerSource in Action
      URL: community/action
      parent: community
      weight: 1
    - name: About
      identifier: about
      URL: about
      weight: 4
    - name: Board & Governance
      URL: about/board
      parent: about
      weight: 1
    - name: Members
      URL: about/members
      parent: about
      weight: 2
    - name: Code of Conduct
      URL: about/codeofconduct
      parent: about
      weight: 3
    - name: Contact Us
      URL: about/contact
      parent: about
      weight: 4
  footer_left:
    - name: Learn
      URL: learn
      weight: 1
      post: bold
    - name: Books
      URL: learn/books
      weight: 2
    - name: Learning Path
      URL: learn/learning-path
      weight: 3
    - name: Patterns
      URL: learn/books/innersource-patterns
      weight: 4
    - name: Research
      URL: learn/research
      weight: 5
  footer_middle:
    - name: Events
      URL: events
      weight: 1
      post: bold
    - name: Community
      URL: community
      weight: 2
      post: bold
      pre: _blank
    - name: InnerSource in Action
      URL: community/action
      weight: 3
  footer_right:
    - name: About
      URL: about
      weight: 1
      post: bold
    - name: Board & Governance
      URL: about/board
      weight: 2
    - name: Members
      URL: about/members
      weight: 3
    - name: Code of Conduct
      URL: about/codeofconduct
      weight: 4
    - name: Contact Us
      URL: about/contact
      weight: 5
    - name: Privacy Policy
      URL: about/privacy
      weight: 6
languages:
  en:
    languageName: English
    weight: 1
  de:
    languageName: Deutsch
    weight: 2
  ja:
    languageName: 日本語
    weight: 2
  zh:
    languageName: 中文
    weight: 2
  it:
    languageName: Italiano
    weight: 2
  es:
    languageName:  Español
    weight: 2
  ru:
    languageName: Русский
    weight: 2
  fr:
    languageName: Français
    weight: 2
paginate: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: true
minify:
  disableHTML: true
params:
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/slick/slick.css
      - link: plugins/youmax/youmax.css
      - link: plugins/bootstrap-select/css/bootstrap-select.min.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/youmax/youmax.js
      - link: plugins/bootstrap-select/js/bootstrap-select.min.js
  logo: images/logo.png
  logo_width: 200px
  themeVariant: quizdown
  description: The InnerSource Commons is a growing community of practitioners with the goal of creating and sharing knowledge about InnerSource.
  author: InnerSource Commons
  footer_content: >-
    The site is licensed under a CC-BY-SA license unless otherwise marked.
  copyright: >-
    Design by [Themefisher](https://themefisher.com/) and [Gethugothemes](https://gethugothemes.com/),
    icons by [Freepik Storyset](https://storyset.com/people)
  preloader:
    enable: false
    preloader: ''
  navigation_button:
    enable: true
    label: Join Slack
    link: slack
  social:
    - title: github
      icon: ti-github
      link: 'http://github.com/InnerSourceCommons'
    - title: youtube
      icon: ti-youtube
      link: 'https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA'
    - title: twitter
      icon: ti-twitter-alt
      link: 'http://twitter.com/InnerSourceOrg'
    - title: linkedin
      icon: ti-linkedin
      link: 'https://linkedin.com/company/innersourcecommons'
