name: github pages

on:
  push:
    branches:
      - master

env:
 HUGO_ENV: "production"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # When this version is updated, it must be also updated at docker-compose.yml
          hugo-version: '0.142.0'
          extended: true
      - name: Copy the missing files from /content/en for publishing each language site
        run: |
          for i in fr ja pt-br; do
            rsync -rv --ignore-existing content/en/ content/$i/ --log-file=content/.gitignore;
            sed -i "s/^.\{37\} /$i\//g" content/.gitignore;
            sed -i '/total size\|file list/d' content/.gitignore;
          done
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public/
